language: node_js

node_js:
  - node

cache: yarn

install:
  - yarn
  - yarn global add codecov

script:
  - travis_retry yarn test --coverage
  - codecov

notifications:
  email:
    on_success: always
    on_failure: always
