name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Get Yarn cache directory
        id: yarn-cache-directory
        run: echo "::set-output name=directory::$(yarn cache dir)"

      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-directory.outputs.directory }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Lint code
        run: yarn lint:eslint && yarn lint:prettier

      - name: Lint package
        run: yarn lint:package
